{% set version = "1.09" %}

package:
  name: libzio
  version: {{ version }}

source:
  url: https://master.dl.sourceforge.net/project/libzio/libzio/libzio-{{ version }}.tar.bz2
  sha256: 588e0eda6c4bb0813d7383d6a69952f1de5796e580852812c1b3e331036e0157
  patches:
    - fix-makefile.diff

build:
  number: 1
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('libzio', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - zlib
    - zstd
    - bzip2
    - xz

test:
  commands:
    - test -f ${PREFIX}/lib/libzio.so.{{ version }}
    - test -f ${PREFIX}/include/zio.h

about:
  home: https://sourceforge.net/projects/libzio/
  summary: 'File stream access for gzip/bzip2/zstd/lzma files'
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
